interface Payment {
  id: number;
  amount: number;
  name: string;
  status: 'Pending' | 'Completed' | 'Rejected';
  description: string;
}

interface Client {
  id: string;
  name: string;
  email: string;
  inn: number;
}

interface User {
  id: number;
  email: string;
  role: 'client' | 'processor';
  password: string;
}

interface FakeData {
  payments: Payment[];
  clients: Client[];
  users: User[];
}

export const fakeData: FakeData = {
  payments: [
    {
      id: 1,
      amount: 1000000,
      name: 'Equipment 1',
      status: 'Pending',
      description: 'to equipments',
    },
    {
      id: 2,
      amount: 15000000,
      name: 'Equipment 2',
      status: 'Completed',
      description: 'to equipments',
    },
    {
      id: 3,
      amount: 7712775,
      name: 'Equipment 3',
      status: 'Rejected',
      description: 'to equipments',
    },
    {
      id: 4,
      amount: 9819519,
      name: 'Equipment 4',
      status: 'Pending',
      description: 'to equipments',
    },
    {
      id: 5,
      amount: 3616026,
      name: 'Equipment 5',
      status: 'Completed',
      description: 'to equipments',
    },
    {
      id: 6,
      amount: 6516864,
      name: 'Equipment 6',
      status: 'Rejected',
      description: 'to equipments',
    },
    {
      id: 7,
      amount: 7140503,
      name: 'Equipment 7',
      status: 'Pending',
      description: 'to equipments',
    },
    {
      id: 8,
      amount: 9587251,
      name: 'Equipment 8',
      status: 'Completed',
      description: 'to equipments',
    },
    {
      id: 9,
      amount: 1251000,
      name: 'Equipment 9',
      status: 'Rejected',
      description: 'to equipments',
    },
    {
      id: 10,
      amount: 7571978,
      name: 'Equipment 10',
      status: 'Pending',
      description: 'to equipments',
    },
    {
      id: 11,
      amount: 10815540,
      name: 'Equipment 11',
      status: 'Completed',
      description: 'to equipments',
    },
    {
      id: 12,
      amount: 8207329,
      name: 'Equipment 12',
      status: 'Rejected',
      description: 'to equipments',
    },
    {
      id: 13,
      amount: 8209488,
      name: 'Equipment 13',
      status: 'Pending',
      description: 'to equipments',
    },
    {
      id: 14,
      amount: 8668213,
      name: 'Equipment 14',
      status: 'Completed',
      description: 'to equipments',
    },
    {
      id: 15,
      amount: 5565984,
      name: 'Equipment 15',
      status: 'Rejected',
      description: 'to equipments',
    },
    {
      id: 16,
      amount: 8572776,
      name: 'Equipment 16',
      status: 'Pending',
      description: 'to equipments',
    },
    {
      id: 17,
      amount: 6937622,
      name: 'Equipment 17',
      status: 'Completed',
      description: 'to equipments',
    },
    {
      id: 18,
      amount: 1545767,
      name: 'Equipment 18',
      status: 'Rejected',
      description: 'to equipments',
    },
    {
      id: 19,
      amount: 8365343,
      name: 'Equipment 19',
      status: 'Pending',
      description: 'to equipments',
    },
    {
      id: 20,
      amount: 5003349,
      name: 'Equipment 20',
      status: 'Completed',
      description: 'to equipments',
    },
    {
      id: 21,
      amount: 5620910,
      name: 'Equipment 21',
      status: 'Rejected',
      description: 'to equipments',
    },
    {
      id: 22,
      amount: 9663877,
      name: 'Equipment 22',
      status: 'Pending',
      description: 'to equipments',
    },
    {
      id: 23,
      amount: 6218097,
      name: 'Equipment 23',
      status: 'Completed',
      description: 'to equipments',
    },
    {
      id: 24,
      amount: 7277869,
      name: 'Equipment 24',
      status: 'Rejected',
      description: 'to equipments',
    },
    {
      id: 25,
      amount: 9610259,
      name: 'Equipment 25',
      status: 'Pending',
      description: 'to equipments',
    },
    {
      id: 26,
      amount: 1000782,
      name: 'Equipment 26',
      status: 'Completed',
      description: 'to equipments',
    },
    {
      id: 27,
      amount: 7130796,
      name: 'Equipment 27',
      status: 'Rejected',
      description: 'to equipments',
    },
    {
      id: 28,
      amount: 2446501,
      name: 'Equipment 28',
      status: 'Pending',
      description: 'to equipments',
    },
    {
      id: 29,
      amount: 9665847,
      name: 'Equipment 29',
      status: 'Completed',
      description: 'to equipments',
    },
    {
      id: 30,
      amount: 9113242,
      name: 'Equipment 30',
      status: 'Rejected',
      description: 'to equipments',
    },
    {
      id: 31,
      amount: 8620227,
      name: 'Equipment 31',
      status: 'Pending',
      description: 'to equipments',
    },
    {
      id: 32,
      amount: 2693170,
      name: 'Equipment 32',
      status: 'Completed',
      description: 'to equipments',
    },
    {
      id: 33,
      amount: 5843190,
      name: 'Equipment 33',
      status: 'Rejected',
      description: 'to equipments',
    },
    {
      id: 34,
      amount: 7163744,
      name: 'Equipment 34',
      status: 'Pending',
      description: 'to equipments',
    },
    {
      id: 35,
      amount: 3642998,
      name: 'Equipment 35',
      status: 'Completed',
      description: 'to equipments',
    },
    {
      id: 36,
      amount: 5623074,
      name: 'Equipment 36',
      status: 'Rejected',
      description: 'to equipments',
    },
    {
      id: 37,
      amount: 9701126,
      name: 'Equipment 37',
      status: 'Pending',
      description: 'to equipments',
    },
    {
      id: 38,
      amount: 5778761,
      name: 'Equipment 38',
      status: 'Completed',
      description: 'to equipments',
    },
    {
      id: 39,
      amount: 8811973,
      name: 'Equipment 39',
      status: 'Rejected',
      description: 'to equipments',
    },
    {
      id: 40,
      amount: 6802531,
      name: 'Equipment 40',
      status: 'Pending',
      description: 'to equipments',
    },
    {
      id: 41,
      amount: 6104517,
      name: 'Equipment 41',
      status: 'Completed',
      description: 'to equipments',
    },
    {
      id: 42,
      amount: 9774336,
      name: 'Equipment 42',
      status: 'Rejected',
      description: 'to equipments',
    },
    {
      id: 43,
      amount: 2864717,
      name: 'Equipment 43',
      status: 'Pending',
      description: 'to equipments',
    },
    {
      id: 44,
      amount: 6826597,
      name: 'Equipment 44',
      status: 'Completed',
      description: 'to equipments',
    },
    {
      id: 45,
      amount: 9146223,
      name: 'Equipment 45',
      status: 'Rejected',
      description: 'to equipments',
    },
    {
      id: 46,
      amount: 2759046,
      name: 'Equipment 46',
      status: 'Pending',
      description: 'to equipments',
    },
    {
      id: 47,
      amount: 9969951,
      name: 'Equipment 47',
      status: 'Completed',
      description: 'to equipments',
    },
    {
      id: 48,
      amount: 10045955,
      name: 'Equipment 48',
      status: 'Rejected',
      description: 'to equipments',
    },
    {
      id: 49,
      amount: 3579053,
      name: 'Equipment 49',
      status: 'Pending',
      description: 'to equipments',
    },
    {
      id: 50,
      amount: 9095884,
      name: 'Equipment 50',
      status: 'Completed',
      description: 'to equipments',
    },
  ],
  clients: [
    {
      id: 'client1',
      name: 'Client 1',
      email: 'client1@example.com',
      inn: 1341235145145,
    },
    {
      id: 'client2',
      name: 'Client 2',
      email: 'client2@example.com',
      inn: 1341235145145,
    },
    {
      id: 'client3',
      inn: 9544343,
      name: 'Client 3',
      email: 'client3@example.com',
    },
    {
      id: 'client4',
      inn: 9809747,
      name: 'Client 4',
      email: 'client4@example.com',
    },
    {
      id: 'client5',
      inn: 2597758,
      name: 'Client 5',
      email: 'client5@example.com',
    },
    {
      id: 'client6',
      inn: 3121150,
      name: 'Client 6',
      email: 'client6@example.com',
    },
    {
      id: 'client7',
      inn: 4535855,
      name: 'Client 7',
      email: 'client7@example.com',
    },
    {
      id: 'client8',
      inn: 8124818,
      name: 'Client 8',
      email: 'client8@example.com',
    },
    {
      id: 'client9',
      inn: 4332819,
      name: 'Client 9',
      email: 'client9@example.com',
    },
    {
      id: 'client10',
      inn: 3776262,
      name: 'Client 10',
      email: 'client10@example.com',
    },
    {
      id: 'client11',
      inn: 8523689,
      name: 'Client 11',
      email: 'client11@example.com',
    },
    {
      id: 'client12',
      inn: 6087268,
      name: 'Client 12',
      email: 'client12@example.com',
    },
    {
      id: 'client13',
      inn: 10656129,
      name: 'Client 13',
      email: 'client13@example.com',
    },
    {
      id: 'client14',
      inn: 5648101,
      name: 'Client 14',
      email: 'client14@example.com',
    },
    {
      id: 'client15',
      inn: 5341136,
      name: 'Client 15',
      email: 'client15@example.com',
    },
    {
      id: 'client16',
      inn: 7078013,
      name: 'Client 16',
      email: 'client16@example.com',
    },
    {
      id: 'client17',
      inn: 3200888,
      name: 'Client 17',
      email: 'client17@example.com',
    },
    {
      id: 'client18',
      inn: 9276767,
      name: 'Client 18',
      email: 'client18@example.com',
    },
    {
      id: 'client19',
      inn: 9899729,
      name: 'Client 19',
      email: 'client19@example.com',
    },
    {
      id: 'client20',
      inn: 9783627,
      name: 'Client 20',
      email: 'client20@example.com',
    },
    {
      id: 'client21',
      inn: 4248230,
      name: 'Client 21',
      email: 'client21@example.com',
    },
    {
      id: 'client22',
      inn: 6633806,
      name: 'Client 22',
      email: 'client22@example.com',
    },
    {
      id: 'client23',
      inn: 7184350,
      name: 'Client 23',
      email: 'client23@example.com',
    },
    {
      id: 'client24',
      inn: 7599261,
      name: 'Client 24',
      email: 'client24@example.com',
    },
    {
      id: 'client25',
      inn: 9102014,
      name: 'Client 25',
      email: 'client25@example.com',
    },
    {
      id: 'client26',
      inn: 7316076,
      name: 'Client 26',
      email: 'client26@example.com',
    },
    {
      id: 'client27',
      inn: 8560067,
      name: 'Client 27',
      email: 'client27@example.com',
    },
    {
      id: 'client28',
      inn: 1225542,
      name: 'Client 28',
      email: 'client28@example.com',
    },
    {
      id: 'client29',
      inn: 6059390,
      name: 'Client 29',
      email: 'client29@example.com',
    },
    {
      id: 'client30',
      inn: 7163359,
      name: 'Client 30',
      email: 'client30@example.com',
    },
    {
      id: 'client31',
      inn: 10096617,
      name: 'Client 31',
      email: 'client31@example.com',
    },
    {
      id: 'client32',
      inn: 4375082,
      name: 'Client 32',
      email: 'client32@example.com',
    },
    {
      id: 'client33',
      inn: 2848051,
      name: 'Client 33',
      email: 'client33@example.com',
    },
    {
      id: 'client34',
      inn: 6130621,
      name: 'Client 34',
      email: 'client34@example.com',
    },
    {
      id: 'client35',
      inn: 2266173,
      name: 'Client 35',
      email: 'client35@example.com',
    },
    {
      id: 'client36',
      inn: 6121632,
      name: 'Client 36',
      email: 'client36@example.com',
    },
    {
      id: 'client37',
      inn: 9078212,
      name: 'Client 37',
      email: 'client37@example.com',
    },
    {
      id: 'client38',
      inn: 1167574,
      name: 'Client 38',
      email: 'client38@example.com',
    },
    {
      id: 'client39',
      inn: 2009592,
      name: 'Client 39',
      email: 'client39@example.com',
    },
    {
      id: 'client40',
      inn: 10926019,
      name: 'Client 40',
      email: 'client40@example.com',
    },
    {
      id: 'client41',
      inn: 2063840,
      name: 'Client 41',
      email: 'client41@example.com',
    },
    {
      id: 'client42',
      inn: 3381938,
      name: 'Client 42',
      email: 'client42@example.com',
    },
    {
      id: 'client43',
      inn: 8086600,
      name: 'Client 43',
      email: 'client43@example.com',
    },
    {
      id: 'client44',
      inn: 10506952,
      name: 'Client 44',
      email: 'client44@example.com',
    },
    {
      id: 'client45',
      inn: 3137729,
      name: 'Client 45',
      email: 'client45@example.com',
    },
    {
      id: 'client46',
      inn: 4907855,
      name: 'Client 46',
      email: 'client46@example.com',
    },
    {
      id: 'client47',
      inn: 10027660,
      name: 'Client 47',
      email: 'client47@example.com',
    },
    {
      id: 'client48',
      inn: 8124995,
      name: 'Client 48',
      email: 'client48@example.com',
    },
    {
      id: 'client49',
      inn: 2050920,
      name: 'Client 49',
      email: 'client49@example.com',
    },
    {
      id: 'client50',
      inn: 10785328,
      name: 'Client 50',
      email: 'client50@example.com',
    },
  ],
  users: [
    {
      id: 1,
      email: 'test@example.com',
      role: 'client',
      password: 'demo',
    },
    {
      id: 2,
      email: 'processor@example.com',
      role: 'processor',
      password: 'demo',
    },
  ],
};
